name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  HELM_REPO: git@github.com:CS464-ECOMMERCE/k8s.git
  HELM_CHART_PATH: ${{ github.event.repository.name }}-chart/helm
  APP_NAME: gitops-argocd-deploy

jobs:
  ##########################
  # ðŸ³ Build & Push Docker #
  ##########################
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --pull -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f docker/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  ######################
  # ðŸ“¦ Update Helm Chart #
  ######################
  update-helm-chart:
    name: Update Helm Chart
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Clone Helm Repository
        run: |
          git clone --single-branch --branch main ${{ env.HELM_REPO }} helm-charts

      - name: Update Helm `values.yaml`
        run: |
          cd helm-charts/${{ env.HELM_CHART_PATH }}
          TAG=$(grep "tag:" values.yaml | awk '{print $2}')
          sed -i "s/$TAG/${{ github.sha }}/" values.yaml
          cat values.yaml

      - name: Commit & Push Helm Changes
        run: |
          cd helm-charts
          git config --global user.name "${{ env.APP_NAME }}"
          git config --global user.email "${{ env.APP_NAME }}@github.com"
          git commit -am "ðŸ”¥ Update image tag to ${{ github.sha }}"
          git push origin main
